### ISSUE TITLE
Produce single (non-animated) wealth histogram

### ISSUE THREAD

**Issue by divilian** [WheezePuppet/specstar#42]
Add code to `sim.jl` to produce a single (non-animated) histogram of agent wealth at simulation's end. (Currently, at fixed number of iterations, but when issue #41 is done, incorporating that logic.)

**Comment by divilian** [comment]
@will-nehrboss: hang tight on this until @venkatachalapathy can communicate to us in a doc exactly what the stopping condition is.

**Comment by venkatachalapathy** [comment]
@WheezePuppet and @will-nehrboss , the first approximation to the full blown stopping condition is easy to implement.  
+ Calculate the pooled wealth among proto-s in a simulation
+ The first time, the proto with the least wealth is able to survive a one-step starvation is the stopping condition

**Comment by wkneh** [comment]
@WheezePuppet @venkatachalapathy Okay...
I think this issue is pretty close to the back of the queue as it depends on the completion of other issues? Once we establish the rules for the starvation shock then we (or just @TromboneDavies  depending on his availability) can get started on implementation of that issue, and only then we can actually code the stopping condition + the end wealth histogram. Correct me if I am wrong, but we need that infrastructure to actually code this issue???

**Comment by venkatachalapathy** [comment]
I think so. Based on my understanding of the code, the proto-s' wealth is never really calculated and accounted for. So, it might take some effort.

**Comment by divilian** [comment]
Reopening this since I think in addition to a histogram of agent wealth, we also want to produce a histogram of proto wealth.

**Comment by wkneh** [comment]
Fixed. (Hopefully)
