### ISSUE TITLE
Determine rules for exogenous "starvation" shock

### ISSUE THREAD

**Issue by divilian** [WheezePuppet/specstar#44]
Figure out and articulate exactly how the simulation should behave to investigate the "how robust are agents & protos to starvation events?" question.

**Comment by divilian** [comment]
Question, @venkatachalapathy: how exactly do we want the simulation to implement the "starvation shock?"

One idea is: add two new simulation parameters, `:start_starv_iter` and `:end_starv_iter`. If (say) the former is 50 and the latter is 60, then during iterations 50 through 60, inclusive, no agent will receive their salary. They will still have their metabolic rate subtracted, as usual, and will still have their white noise up-or-down, as usual.

Does this sound reasonable for phase 1?

**Comment by venkatachalapathy** [comment]
My idea is to first code up the stopping rule; then implement _a starvation rule_ like the one you suggested.  The stopping rule is a separate issue #41 that I closed because we have a constructive definition for it. So, in #45, we have to algorithmize both the _stopping conditions_ and _starvation rules_. 

Both are doable but is this what we want to be spend our time on between now and our end of the month deadline, @WheezePuppet and @will-nehrboss ?

**Comment by divilian** [comment]
Ah, that makes sense.

And yes I do think we want to prioritize this for phase 1, in part because I don't actually think it will take that long to code, once we figure out exactly what to code.

**Comment by divilian** [comment]
As of yesterday's Zoom call, we have decided on the following for phase 1.

Every simulation can be divided into three stages:
S1. The iterations before any agents create a proto.
S2. The iterations during which agents create and join protos.
S3. The iterations after which all agents are either (a) graph isolates, (b) dead, or (c) in a proto.

The "stopping condition" is when S2 transitions to S3.
